-- CREATE DATABASE 
CREATE DATABASE RETAIL_DB;

-- PRODUCTS TABLE
CREATE TABLE
    IF NOT EXISTS PRODUCTS (
        ProductID INT (11) PRIMARY KEY AUTO_INCREMENT,
        ProductName VARCHAR(255) NOT NULL,
        Price DECIMAL(11, 11) NOT NULL,
        StockQuantity INT (11) DEFAULT 0,
        SupplierID INT (11) NOT NULL,
        FOREIGN KEY (SupplierID) REFERENCES SUPPLIERS (SupplierID) ON DELETE CASCADE ON UPDATE CASCADE,
        CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        UpdatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
        DeletedAt TIMESTAMP NULL DEFAULT NULL
    );

-- SUPPLIERS TABLE
CREATE TABLE
    IF NOT EXISTS SUPPLIERS (
        SupplierID INT (11) PRIMARY KEY AUTO_INCREMENT,
        SupplierName VARCHAR(255) NOT NULL,
        ContactNumber VARCHAR(20) NOT NULL,
        CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        UpdatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
        DeletedAt TIMESTAMP NULL DEFAULT NULL
    );

-- SALES TABLE
CREATE TABLE
    IF NOT EXISTS SALES (
        SaleID INT (11) PRIMARY KEY AUTO_INCREMENT,
        ProductID INT (11) NOT NULL,
        QuantitySold INT (11) DEFAULT 0,
        SaleDate DATE,
        FOREIGN KEY (ProductID) REFERENCES PRODUCTS (ProductID) ON DELETE CASCADE ON UPDATE CASCADE,
        CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        UpdatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
        DeletedAt TIMESTAMP NULL DEFAULT NULL
    );